### ISSUE TITLE
【勘误】Page 13 的最后一道习题340难度是中等

### ISSUE THREAD

**Issue by suclogger** [changgyhub/leetcode_101#15]
![image](https://user-images.githubusercontent.com/8472155/105752369-2c62ed00-5f82-11eb-9cb2-83bd57fd3857.png)

**Comment by changgyhub** [comment]
感谢指错。
此题在成文时仍为hard，我目前已无leetcode会员，等之后确认后再统一修改吧。

**Comment by shm007g** [comment]
跟一个: page 19, 闭区间的quicksort结束条件应该是r - l <= 0而不是1。

**Comment by XingHong** [comment]
![image](https://user-images.githubusercontent.com/4038425/121761983-d488e500-cb22-11eb-9adc-be60479ed7d8.png)
类似的也有习题99，已经不是hard

**Comment by changgyhub** [comment]
谢谢大家的关注。

由于我早已开始全职工作，这个书我并不打算长期维护，所以涉及题目更换、难度变化的更新请求不再回复。
