### ISSUE TITLE
【勘误】455. Assign Cookies (Easy)

### ISSUE THREAD

**Issue by cluckl** [changgyhub/leetcode_101#16]
原题的题意应该包含孩子的饥饿度等于饼干的大小也符合题中要求，并且在你的代码中：
if (children[child] <= cookies[cookie]) ++child;
体现出了两者等于的情况。
**但是在你的题目描述中没有包含该情况。**
![Snipaste_2021-02-14_02-38-19](https://user-images.githubusercontent.com/46401606/107858301-8f072480-6e6e-11eb-9e1c-732b73ae7c42.jpg)

**Comment by changgyhub** [comment]
您好，可能您的版本有点老，此问题在最新版本书中已被纠正。谢谢参与讨论
