### ISSUE TITLE
很棒的书，不知道作者有没有加入Java版和Python版的想法？

### ISSUE THREAD

**Issue by mayitbeegh** [changgyhub/leetcode_101#19]

**Comment by changgyhub** [comment]
没时间写 - -

**Comment by shm007g** [comment]
我在刷Python版本的，刷完了可以合作。

@changgyhub 首先感谢大神。然后我想问问，每个小版本更新了啥，好像没有写，是勘误吗？

**Comment by XuRunheng** [comment]
附议 可以开放其他语言的版本 
作者没时间写可以让大家贡献代码+（解释）即可
作者就负责审核 甚至审核也可以交给信任的人

**Comment by Rwadxvv** [comment]
نؤنس

**Comment by changgyhub** [comment]
2.0版会有python。Java和C++相似度太大了，至少可见的未来我不太会加入Java版本。
