### ISSUE TITLE
可能的问题

### ISSUE THREAD

**Issue by CG-banana** [changgyhub/leetcode_101#21]
在背包问题中的注意段落 最后一句写 “完全背包对物品的迭代放在里层，外层的体积或价值正向遍历。”  作者的code写的也是外层是物品的贴袋 内层是体积或者价值， 不知道是我理解错了还是这里没写清楚，请指正。

谢谢分享这本书给大家。

**Comment by changgyhub** [comment]
谢谢支持！当二维DP问题行和列可以互换的时候，内外都可以，这个还是要具体情况具体分析，建议画出状态转移矩阵或写出状态转移方程辅助判断。
