### ISSUE TITLE
【勘误】回溯法 46. Permutation 页码30/143 

### ISSUE THREAD

**Issue by Jackory** [changgyhub/leetcode_101#24]
以样例 [1,2,3]为例，输出数组的顺序为[[1,2,3],[1,3,2],[2,1,3],[2,3,1],**[3,2,1],[3,1,2]**]；而非[[1,2,3],[1,3,2],[2,1,3],[2,3,1],**[3,1,2],[3,2,1]**]

**Comment by changgyhub** [comment]
您好，您用我提供的算法，输出顺序确实是[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,2,1],[3,1,2]]。[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]是题目提供的一种输出顺序，以任意顺序输出都可以。
