### ISSUE TITLE
【勘误】7.2的例题198解答处有点小问题，状态转移方程看上去有点小问题。

### ISSUE THREAD

**Issue by JPQAQ** [changgyhub/leetcode_101#25]
![图片](https://user-images.githubusercontent.com/73947152/111953018-faed4480-8b20-11eb-9c7a-398dcdd20e62.png)
应该是dp[i] = max(dp[i-1],nums[i] + dp[i-2])吧。
下面的代码部分也是如此。

**Comment by changgyhub** [comment]
谢谢提问，答案应该是没有问题的，只是怎么定义num的i和i-1的问题。
