### ISSUE TITLE
could you attatch the book in this post or put it in realase? 

### ISSUE THREAD

**Issue by l1t1** [changgyhub/leetcode_101#27]
cannot visit following link

https://github.com/changgyhub/leetcode_101/blob/master/LeetCode%20101%20-%20A%20LeetCode%20Grinding%20Guide%20(C%2B%2B%20Version).pdf

**Comment by changgyhub** [comment]
I see no problem clicking into that link :)

**Comment by l1t1** [comment]
it works now. 
but it often does not work. 
github.com is more stable than raw.githubusercontent.com.

**Comment by changgyhub** [comment]
Sorry I don't understand your point. Didn't you use the link starting with github.com?

**Comment by l1t1** [comment]
if you run 
wget  https://github.com/changgyhub/leetcode_101/raw/master/LeetCode%20101%20-%20A%20LeetCode%20Grinding%20Guide%20(C%2B%2B%20Version).pdf

you will see returns 302 code and redirects to another domain

**Comment by l1t1** [comment]
if you run 
wget  https://github.com/changgyhub/leetcode_101/raw/master/LeetCode%20101%20-%20A%20LeetCode%20Grinding%20Guide%20(C%2B%2B%20Version).pdf

you will see returns 302 code and redirects to another domain

**Comment by changgyhub** [comment]
Again, what is your point?

> cannot visit following link
> https://github.com/changgyhub/leetcode_101/blob/master/LeetCode%20101%20-%20A%20LeetCode%20Grinding%20Guide%20(C%2B%2B%20Version).pdf

If you cannot access github.com, then it's not the fault of this repo.

> it works now.
> but it often does not work.
> github.com is more stable than raw.githubusercontent.com.

Your link is not raw.githubusercontent.com.

> if you run
> wget https://github.com/changgyhub/leetcode_101/raw/master/LeetCode%20101%20-%20A%20LeetCode%20Grinding%20Guide%20(C%2B%2B%20Version).pdf
> you will see returns 302 code and redirects to another domain

That just a web page ending in .pdf. You are not supposed to wget it.
But if you do, you will see the link gets redirected to https://raw.githubusercontent.com/changgyhub/leetcode_101/master/LeetCode%20101%20-%20A%20LeetCode%20Grinding%20Guide%20(C%2B%2B%20Version).pdf, which is where github stores files. That means wget-ing either one will let you download the pdf file.

**Comment by l1t1** [comment]
if the file be put on the release section, the link will be sth like https://github.com/lightvector/KataGo/releases/download/v1.8.1/katago-v1.8.1-cuda11.1-linux-x64.zip .and will not redirect to raw.githubusercontent.com

if the file be put as an attachment.  the link will be sth like https://github.com/lightvector/KataGo/files/6218062/katagoLBSU.zip . it won't redirect either.  

so I request the file be put  on this two places.

**Comment by l1t1** [comment]
http://blog.sina.cn/dpool/blog/s/blog_c2972c530102z0f9.html described the  problem of raw.githubusercontent.com.
but I cannot do that on the phone

**Comment by l1t1** [comment]
anyway.  I already download the file when it works.  thanks for your nice work.

**Comment by l1t1** [comment]
and another easy way to download all the files.
go to the code section and click green button. download the zip file also works.  the link is
https://github.com/changgyhub/leetcode_101/archive/refs/heads/master.zip

**Comment by changgyhub** [comment]
I am confused. I encourage you to check what you have commented yourself. I cannot find the logic.

Are you teaching me how to download files? Well then, thank you?
Are you correcting me? I ain't say anything like "you must download with this link".
Are you suggesting me to put my files in the release? Okay, but I just don't feel it necessary. There's tons of ways to download a file. Do you think it is easier for a newbie to just click the repo and read through browser, or wget a master.zip?

**Comment by changgyhub** [comment]
Re-open this issue to see if anyone can help.

**Comment by l1t1** [comment]
sorry for disturbing you so many times.
in short, the file stored in githubusercontent.com is harder to download for **me** .because of dns or other questions. so I want the stored in other places easier to download for **me**.
