### ISSUE TITLE
p17页leetcode 81题 ++l 方式已无法通过当前的测试样例

### ISSUE THREAD

**Issue by smartmark-pro** [changgyhub/leetcode_101#30]
样例如下
```
[1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1]
2
```
可以在二分while下， 使用 while的形式， 左移和右移过滤掉相同的数字
事实上， 该题复杂度是O（n）的话， for循环可能更好一点， 二分太折磨人了

**Comment by changgyhub** [comment]
您再看一下？我这边是可以的。

![WeChat Screenshot_20210413025751](https://user-images.githubusercontent.com/14730912/114534683-1c16f180-9c04-11eb-8784-14a539811e20.png)

书里很多题目其实都有多种解法，介绍二分就是为了展示二分的用法:)

**Comment by smartmark-pro** [comment]
抱歉, 我看了下, 是自己的失误.
我复制下来, 测试的时候, 少去掉一个//
最后感谢作者, 书写的非常好
