### ISSUE TITLE
关于用什么排版

### ISSUE THREAD

**Issue by Xu-pixel** [changgyhub/leetcode_101#31]
请问制作一本这样的pdf书是用什么排版的

**Comment by smartmark-pro** [comment]
[Latex](https://baike.baidu.com/item/LaTeX/1212106?fr=aladdin) , 前言中有提到,  其实了解出版和学术的话, 应该也能想到的.
如果作者愿意分享模板的话, 我也想得到一份.:smile:

**Comment by changgyhub** [comment]
https://www.overleaf.com/latex/templates/elegantbook-template/zpsrbmdsxrgy

**Comment by smartmark-pro** [comment]
没想到模板, 就叫elegantbook, 我还以为是作者的溢美之词. 顺便star了

**Comment by Xu-pixel** [comment]
感谢
