### ISSUE TITLE
关于中文书名的小疑问

### ISSUE THREAD

**Issue by jacklanda** [changgyhub/leetcode_101#41]
这个问题可能不值得开issue，它就是一个关于书名的小疑问：
为什么不叫”....和你一起轻松刷题“，而是”和你一起你轻松刷题“（有点别扭）呢？
刚下载打开看的时候，还以为下到了”二次排版“的盗版PDF。

**Comment by changgyhub** [comment]
我不确定是不是我太久不学语文了，主语省略应该是一个正常现象？这里的主语应该是书/作者。

**Comment by plkdsy** [comment]
读起来的确很奇怪，多个“你”

**Comment by TubaVADE** [comment]
I found that solution is very popular and helpful : https://youtu.be/KIoM0FEZ0IA

**Comment by changgyhub** [comment]
第二版会重命名书名
