### ISSUE TITLE
【勘误】笔误

### ISSUE THREAD

**Issue by KivenGood** [changgyhub/leetcode_101#42]
![1620098853(1)](https://user-images.githubusercontent.com/28687350/116958074-01e4a680-accc-11eb-8fa8-8804b1379043.jpg)
此处应该是笔误吧！

**Comment by changgyhub** [comment]
请问哪里笔误？没看出来lol

**Comment by KivenGood** [comment]
再看一遍确实没问题，但是确实在我不了解并查集时看这段比较费力，学完后回来才有能看懂。😂
