### ISSUE TITLE
P56 322、Coin Change

### ISSUE THREAD

**Issue by hitYunhongXu** [changgyhub/leetcode_101#43]
您好，在P56的322题中，我觉得结果的最大可取值应该为amount，也就是全部都用面额为1的硬币，所以dp的初始值应该可以为amount+1，（当然amount+2也可以～）。或者说这里还有其他需要考虑的地方，导致只能取amount+2?谢谢。

**Comment by changgyhub** [comment]
确实，下个版本会更正，谢谢！
