### ISSUE TITLE
error: use of class template 'hash' requires template arguments, page 94-95.

### ISSUE THREAD

**Issue by chuck-tz** [changgyhub/leetcode_101#48]
When I compiled the code using -std=c++11, I got the following error:
error: use of class template 'hash' requires template arguments
        return hash(obj, hash_table.size());
I'm thinking there would be an implicit type casting involved in the myhash's call to hash. Would that be the problem?

Btw, I really admire your work and it has helped me a ton!

**Comment by changgyhub** [comment]
I changed the code a bit and it should work now, PTAL.
