### ISSUE TITLE
[疑问]100页，题目304的变化

### ISSUE THREAD

**Issue by XingHong** [changgyhub/leetcode_101#52]
貌似修改了测试用例，作者的方法在该题目中超时了。

**Comment by changgyhub** [comment]
刚刚交了一下，AC了，不过确实有点慢。

可能测试用例改成了每次都重建NumMatrix导致建图的时间占了大部分，而不是少次建图+多次query。如果你去重新跑一下大家比较快的那些代码也会有时超时。所以应该不是书里答案本身的问题。
