### ISSUE TITLE
第16页， Leetcode 34 题，你用的应该是“左开右闭”的binary search，但是你写成了“左闭右开”

### ISSUE THREAD

**Issue by changhanxie** [changgyhub/leetcode_101#53]
我也不确定我理解的是不是对的，所以专门确认了一下左开右闭和左闭右开的区别。
下面这个链接有提到。
https://blog.csdn.net/m0_37302219/article/details/107180126

**Comment by changgyhub** [comment]
你发的这个链接的评论区都说了，博主写错了，应该是左闭右开而不是左开右闭......
左闭右开=[start, end)

**Comment by changhanxie** [comment]
没注意看评论，抱歉。我当时也挺迷的。
