### ISSUE TITLE
一些leetcode的更新和Java代码

### ISSUE THREAD

**Issue by changhanxie** [changgyhub/leetcode_101#54]
Leetcode上的题目名字和难度更新：
695题现在从easy变成mid了
547题以前叫Friend Circles，现在叫Number of Provinces
198题 house robber(easy) 现在是mid

Java代码：
最近在做leetcode，就跟着你的书翻译了一部分java code，你可以先拿去用。我之后会尽量补全缺的部分。
https://github.com/changhanxie/Leetcode101-JavaCode.git

**Comment by changgyhub** [comment]
感谢你的关注。

由于我早已开始全职工作，这个书我并不打算长期维护，所以涉及题目更换、难度变化的更新请求不再回复。

至于java版本，您可以关注[CyC2018的LeetCode题解](https://github.com/CyC2018/CS-Notes/blob/master/notes/Leetcode%20%E9%A2%98%E8%A7%A3%20-%20%E7%9B%AE%E5%BD%95.md)，其主要内容和本书重合度很高，也是我写此书最开始借鉴的文档。
