### ISSUE TITLE
7.6背包问题中的416题不进行空间压缩的代码在Leetcode测试用例中没有全部通过

### ISSUE THREAD

**Issue by yijicheng** [changgyhub/leetcode_101#57]
![image](https://user-images.githubusercontent.com/53086386/143032608-ec89a04b-dbac-49e7-bc5d-ee6eb54fac2d.png)

**Comment by changgyhub** [comment]
同学，你可能看的是老版本？目前版本的代码和你写的不太一样，我刚刚测了可以跑通的。
