### ISSUE TITLE
关于二进制文件放在release页面更好这件事

### ISSUE THREAD

**Issue by lingr7** [changgyhub/leetcode_101#6]
感谢作者。尤其是使用了

> ElegantBook提供的精美LATEX模版

几年前我看到这个模板，我就一直想用这个模板排版点内容啥的，做做笔记之类的，不过一直没有合适的内容。
现在看到作者的成品，就像cuda程序员还顺手写了opencl实现一样，让我觉得非常高兴。

但是把pdf这种二进制文件用git管理确实不太方便啊。正好tex用法也可以理解为编译，pdf是编译出的二进制文件，那么放在release环节更加自然。

**Comment by changgyhub** [comment]
目前没有开放源码的计划，抱歉。
