### ISSUE TITLE
Typo in section 11.7 (Page 97)

### ISSUE THREAD

**Issue by conan81412B** [changgyhub/leetcode_101#62]
Hi, it's me again :)

There is a typo at the top of page 97 (version 4c7af46cc7259ab23407131bbb1ffb6b2cd08e9b):
给定一些二维坐标中的点，求同一条线上最多**由**多少点
should be
给定一些二维坐标中的点，求同一条线上最多**有**多少点

**Comment by changgyhub** [comment]
Thank you! Will fix in 1.16.
