### ISSUE TITLE
第35页最下方，解答中可能少了一条语句。

### ISSUE THREAD

**Issue by XiangYG** [changgyhub/leetcode_101#63]
在35页倒数第四行的  points.pop();   语句前我认为应该加上一句  grid[r][c]=2;   。
不加这一句也能得到正确的答案，但是按照写的解题思路”bfs寻找第二个岛屿，并把过程中经过的0赋值为2“来说，是需要这一语句的。
我在下面上传了截图，不知道你能不能看到。同样，很感谢你的书。
![1](https://user-images.githubusercontent.com/101644637/159252367-9a6a7e24-8da4-418b-a8f1-a929bc891bb5.png)

**Comment by changgyhub** [comment]
有道理，谢谢！
