### ISSUE TITLE
内容勘误

### ISSUE THREAD

**Issue by jacklanda** [changgyhub/leetcode_101#70]
于阅读过程中，发现诸多 typo，是否需要单独开一个 issue 供大家集中提交&讨论呢？

**Comment by changgyhub** [comment]
您好，感谢支持，可否说明一下哪里有误？

**Comment by jacklanda** [comment]
> 您好，感谢支持，可否说明一下哪里有误？

e.g., p24 中 6.2 深度优先搜索 小节标题下的第一段 “深度优先搜索 (depth-first seach, DFS)” 处的 seach 应为 search；
        p24 中 695. Max Area of Island (Easy) 该题应为 Medium 而非 Easu.

**Comment by changgyhub** [comment]
(1) 好的，下个版本即更正
(2) 题目难度leetcode会自己变更，所以本书的难度以成书时为准
