### ISSUE TITLE
关于贪婪法

### ISSUE THREAD

**Issue by xnervwang** [changgyhub/leetcode_101#72]
建议作者在贪婪法一章标明，证明一道题能用贪婪法解决，有时远比用贪婪法解决该题更复杂。。。
例如452. Minimum Number of Arrows to Burst Balloons这道题，当某个气球分别和另外两个气球有重叠区域时，很难直接理解为什么贪婪法的选择能奏效。说不定选择另一个重叠区域比选择当前重叠区域，最终使用的箭数更少呢？
感觉贪婪法的题目最终考察的是以前是否看过原题，否则除非是很简单的题目，否则短时间内很难想到是用贪婪法，或者说无法去证明能用贪婪法解决。

**Comment by changgyhub** [comment]
好的，马上改
