### ISSUE TITLE
Typo勘误, Section 16.3, Page 141. Version 1.21

### ISSUE THREAD

**Issue by zhangwang997** [changgyhub/leetcode_101#78]
内容141页（PDF文件的147页），16.3 复合数据结构::题解::第四行，**cash** hit是否应为**cache** hit？

Version 1.21, Jun 17 2022

![image](https://user-images.githubusercontent.com/48432934/185027859-c67f8700-2c85-46fc-a070-8f62efa59c8a.png)

同时感谢您的分享！这对我学习算法帮助很大。

**Comment by changgyhub** [comment]
感谢指正
