### ISSUE TITLE
P102 第225题的TYPO

### ISSUE THREAD

**Issue by MoyuST** [changgyhub/leetcode_101#83]
P102练习部分的第225题有个小小笔误，但是无伤大雅，只是正好看到了想提一提
![image](https://user-images.githubusercontent.com/46509809/235344085-99a7d8ee-b43e-4e6d-8518-65e4a5171f52.png)
划线部分的stack应该和queue颠倒一下，应该为“利用相似的方法，我们也可以用 queue 实现 stack。”

**Comment by changgyhub** [comment]
感谢！2.0版本即将更正。
