### ISSUE TITLE
23.9.21 I Cannot download your 《LeetCode 101 - A LeetCode Grinding Guide (C++ Version).pdf》

### ISSUE THREAD

**Issue by KanameMadoka520** [changgyhub/leetcode_101#85]
![无法下载](https://github.com/changgyhub/leetcode_101/assets/90090108/536969fc-c642-4ee4-87b1-b62d90058b53)
![无法下载2](https://github.com/changgyhub/leetcode_101/assets/90090108/ce944c8f-2f1e-42d1-baec-ef6a26dff525)
May I get some advice to solve this?Really longing for such a nice book.
Appreciate it if you could help me.

**Comment by Bayonetta** [comment]
用梯子或加速器，改hosts等等很多方法，国内网络直连有问题
